# Generated by Django 4.2.1 on 2023-06-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cen_id', models.IntegerField()),
                ('slot_coun', models.IntegerField()),
                ('cen_name', models.CharField(max_length=200)),
                ('cen_loc_city', models.TextField(blank=None, null=True)),
                ('cen_loc_dis', models.CharField(max_length=200)),
                ('dat_t', models.DateTimeField(auto_now=True)),
                ('cre_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
