# Generated by Django 4.2.1 on 2023-06-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacbok', '0002_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('vaccine_center', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('book_date', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('cre_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
