# Generated by Django 4.2.1 on 2023-06-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacbok', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='e_mail',
            field=models.CharField(default='', max_length=100),
        ),
    ]
